# Generated by Django 5.2.3 on 2025-09-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='great',
            old_name='created_at',
            new_name='date',
        ),
    ]
