# Generated by Django 5.2.3 on 2025-09-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0002_rename_created_at_great_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='great',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
