# Generated by Django 5.2.3 on 2025-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0003_alter_great_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='great',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='great',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='great',
            name='number_of_interns_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='great',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='great',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
