# Generated by Django 5.2.3 on 2025-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0004_great_address_great_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='great',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
