# Generated by Django 5.2.3 on 2025-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0005_alter_great_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='great',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
