# Generated by Django 5.2.3 on 2025-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0006_alter_great_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='great',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='great',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
