# Generated by Django 5.2.3 on 2025-09-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0007_great_is_verified_great_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.TextField()),
                ('internship_location', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('past_participation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('skills_required', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
    ]
