# Generated by Django 5.2.3 on 2025-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0008_candidate_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='great',
            name='address',
        ),
        migrations.AddField(
            model_name='great',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
